# %% [markdown]
# **Part 1: Hardware-Aware MLP Search:** We will first run a search on a single, well-defined architecture type (MLP). This allows us to use accurate, model-based hardware performance estimators (`rule4ml`) and visualize the complex trade-offs between accuracy, BOPs, and hardware resources.
# 

# %%

import os
import yaml
import tensorflow as tf
import pandas as pd

# Import the necessary search functions and visualization tools from the library
# Note: We import from two different modules to showcase both search types
# from utils.tf_global_search import run_mlp_search
from utils.tf_global_search5 import GlobalSearchTF, run_mlp_search
from utils.tf_visualization import plot_pareto_fronts, plot_3d_pareto_front_heatmap
from utils.tf_local_search1 import local_search_entrypoint # NEW
from utils.tf_data_preprocessing import load_and_preprocess_mnist


# Use matplotlib for inline plotting in notebooks
%matplotlib inline

# Suppress TensorFlow logging for cleaner output
tf.get_logger().setLevel('ERROR')

# %%
# ## Part 1: MLP-Only Hardware-Aware Search
#
# In this section, we'll perform a search over standard MLP architectures. Because the structure is well-defined, we can use hardware-aware estimators to get realistic performance metrics for FPGAs. This allows for a 4-objective optimization.

# %%
# --- Configuration for Global Search ---
N_TRIALS_HYBRID = 15
EPOCHS_HYBRID = 10
SUBSET_SIZE_HYBRID = 40000
RESULTS_DIR_HYBRID = "./results/Newhybrid_search_tutorial"
SEARCH_SPACE_PATH = 'hybrid_search_space.yaml'

# --- Objectives for Hybrid Search (Performance vs. Cost) ---
OBJECTIVE_NAMES_HYBRID = ['performance_metric', 'bops']
MAXIMIZE_FLAGS_HYBRID = [True, False]
OBJECTIVE_INFO_HYBRID = list(zip(OBJECTIVE_NAMES_HYBRID, MAXIMIZE_FLAGS_HYBRID))

os.makedirs(RESULTS_DIR_HYBRID, exist_ok=True)

# --- Create the YAML configuration file for the hybrid search ---
search_space_yaml = """
search_spaces:
  channel_space: [8, 16, 32]
  mlp_width_space: [32, 64, 128]
  kernel_space: [1, 3, 5]
  act_space: ["ReLU", "GELU"]
  norm_space: [null, "batch"]
  block_types: ["Conv", "MLP", "None"]
hyperparameters:
  num_blocks: 4
  initial_img_size: 11
  output_dim: 10
"""
with open(SEARCH_SPACE_PATH, 'w') as f:
    f.write(search_space_yaml)
print(f"Created search space configuration file: {SEARCH_SPACE_PATH}")



# %%
# --- Run the Hybrid Global Search ---
print("\n" + "="*50)
print("Running Part 1: Hybrid Architecture Global Search...")
print("="*50)

with open(SEARCH_SPACE_PATH, 'r') as f:
    config = yaml.safe_load(f)
search_space_simple = config.get('search_spaces', {})
search_space_simple.update(config.get('hyperparameters', {}))

searcher_simple = GlobalSearchTF(results_dir=RESULTS_DIR_HYBRID)
searcher_simple.search_space = search_space_simple

study_simple = searcher_simple.run_search(
    model_type='block',
    n_trials=N_TRIALS_HYBRID,
    epochs=EPOCHS_HYBRID,
    dataset='mnist',
    subset_size=SUBSET_SIZE_HYBRID,
    resize_val=searcher_simple.search_space.get('initial_img_size', 11),
    objectives=OBJECTIVE_NAMES_HYBRID,
    maximize_flags=MAXIMIZE_FLAGS_HYBRID,
    verbose=True
)


# %%
print("\n" + "="*50)
print("ANALYZING GLOBAL SEARCH RESULTS")
print("="*50)

results_df_hybrid = pd.DataFrame(searcher_simple.results)

if not results_df_hybrid.empty:
    print("\n--- Generating Pareto Front Plots for Global Search ---")
    plot_pareto_fronts(results_df_hybrid, OBJECTIVE_INFO_HYBRID, save_dir=searcher_simple.results_dir)
    print(f"\nGlobal search plots saved to: {searcher_simple.results_dir}")
else:
    print("Global search did not yield any results to analyze.")


# %%
# ## Part 2: Automated Local Search (QAT + Pruning)
# 
# Now, we take the `best_model_for_local_search.yaml` file that was automatically generated by the global search and run it through the local search pipeline.

# %%
# --- Configuration for Local Search ---
LOCAL_SEARCH_RESULTS_DIR = "./results/local_search_tutorial"
LOCAL_SEARCH_CONFIG_PATH = 'local_search_settings.yaml'

# Define the settings for the local search (precisions, pruning, etc.)
local_search_settings = {
    'precision_pairs': [
        {'total_bits': 16, 'int_bits': 6},
        {'total_bits': 8, 'int_bits': 3},
        {'total_bits': 4, 'int_bits': 1},
    ],
    'pruning_iterations': 7,
    'epochs_per_iteration': 10,
    'pruning_rate': 0.8, # Prune 20% of remaining weights each iteration (1 - 0.8)
}

# Write the settings to a YAML file
with open(LOCAL_SEARCH_CONFIG_PATH, 'w') as f:
    yaml.dump(local_search_settings, f)
print(f"Created local search configuration file: {LOCAL_SEARCH_CONFIG_PATH}")

# Path to the best model found by the global search
ARCHITECTURE_YAML_PATH = os.path.join(RESULTS_DIR_HYBRID, "best_model_for_local_search.yaml")

# --- Load Dataset for Local Search ---
# Ensure we use the same data preprocessing as the global search
resize_val = searcher_simple.search_space.get('initial_img_size', 11)
x_train, y_train, x_val, y_val = load_and_preprocess_mnist(
    resize_val=resize_val, 
    subset_size=SUBSET_SIZE_HYBRID, 
    flatten=False,
    one_hot=False
)


# %%
if os.path.exists(ARCHITECTURE_YAML_PATH):
    local_search_df = local_search_entrypoint(
        architecture_yaml_path=ARCHITECTURE_YAML_PATH,
        local_search_config_path=LOCAL_SEARCH_CONFIG_PATH,
        dataset=(x_train, y_train, x_val, y_val),
        results_dir=LOCAL_SEARCH_RESULTS_DIR
    )
else:
    print(f"ERROR: Could not find the architecture file: {ARCHITECTURE_YAML_PATH}")
    print("Please ensure the global search ran successfully.")
    local_search_df = pd.DataFrame()



# %%


# %%



